name: digital_cert_auth_fixed
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter  # 这里只保留 sdk 声明

  cupertino_icons: ^1.0.8
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  google_sign_in: ^6.3.0
  file_picker: ^8.0.2
  open_filex: ^4.7.0
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  uuid: ^4.3.3
  pdf: ^3.10.7
  url_launcher: ^6.1.11
  intl: ^0.18.1
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png  # 正确的 assets 声明位置